name: Gradle Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ vars.JAVA_VERSION }}
    outputs:
      head_commit_id: ${{ steps.get_head_commit_id.outputs.head_commit_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get head commit id
        id: get_head_commit_id
        run: |
          HEAD_COMMIT_ID=$(git rev-parse HEAD)
          echo "head_commit_id=$HEAD_COMMIT_ID" >> $GITHUB_OUTPUT

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          check-latest: true
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Run test task
        run: ./gradlew test --no-daemon
      
      - name: Upload test reports artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test/
          retention-days: 1

      - name: Run javadoc task
        run: ./gradlew javadoc --no-daemon

      - name: Upload javadoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: build/docs/javadoc/
          retention-days: 1

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download test reports artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: gh-pages/test

      - name: Download javadoc artifacts
        uses: actions/download-artifact@v4
        with:
          name: javadoc
          path: gh-pages/api-docs

      - name: Commit and push to gh-pages
        run: |
          HEAD_COMMIT_ID=${{ needs.test.outputs.head_commit_id }}
          cd gh-pages
          git init .
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Deployed $HEAD_COMMIT_ID with Gradle test task"
          git branch -M gh-pages
          git push -f -u origin gh-pages
