name: Gradle Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ vars.JAVA_VERSION }} != ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          check-latest: true
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Run test task
        run: ./gradlew test --no-daemon
      
      - name: Upload reports artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: build/reports/tests/test/
          retention-days: 3

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git init .
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Download reports artifacts
        uses: actions/download-artifact@v4
        with:
          name: test
          path: test

      - run: |
          git add .
          git commit -m "Update test reports"
          git branch -M gh-pages
          git push -u origin gh-pages
